export const SET_SESSION = 'SET_SESSION';
export const UNSET_SESSION = 'UNSET_SESSION';
export const SET_IS_LOGIN = 'SET_IS_LOGIN';
export const UNSET_IS_LOGIN = 'UNSET_IS_LOGIN';

export const USER_INFO = 'USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_PORTFOLIO = 'SET_USER_PORTFOLIO';
export const UPDATE_USER_PORTFOLIO = 'UPDATE_USER_PORTFOLIO';
export const SET_WATCH_LIST = 'SET_WATCH_LIST';

// export const SET_SHARE_INFORMATION = 'SET_SHARE_INFORMATION';
export const SET_SID = 'SET_SID';

//Status
export const SET_STATUS = 'SET_STATUS';

//Buying power
export const SET_BUYING_POWER = 'SET_BUYING_POWER';

//Time
export const SET_TIME = 'SET_TIME';

//Order book
export const ORDER_BOOK = 'ORDER_BOOK';
export const SET_ORDER_BOOK = 'SET_ORDER_BOOK';
export const SET_ORDER_BOOK_ORDERS = 'SET_ORDER_BOOK_ORDERS';
export const SET_ORDER_BOOK_ORDERS_VISIBILITY = 'SET_ORDER_BOOK_ORDERS_VISIBILITY';
export const UPDATE_ORDER_BOOK_HAS_ORDER = 'UPDATE_ORDER_BOOK_HAS_ORDER';

//Order
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const SET_QUEUED_ORDER = 'SET_QUEUED_ORDER';
export const SET_FINISH_ORDER = 'SET_FINISH_ORDER';
export const SET_CALC_TRADE = 'SET_CALC_TRADE';
export const SET_CALC_ORDER = 'SET_CALC_ORDER';

//available shares
export const SET_AVAILABLE_SHARE = 'SET_AVAILABLE_SHARE';
export const AVAILABLE_SHARE = 'AVAILABLE_SHARE';

export const SHARES_INFO = 'SHARES_INFO';
export const SET_SHARES_INFO = 'SET_SHARES_INFO';

export const UPDATE_SHARE_INFO = 'UPDATE_SHARE_INFO';
export const SET_UPDATE_SHARE_INFO = 'SET_UPDATE_SHARE_INFO';

export const SHARE_STATUS_CHANGE = 'SHARE_STATUS_CHANGE';
export const SET_SHARE_STATUS_CHANGE = 'SET_SHARE_STATUS_CHANGE';

//select instrument
export const SET_SELECTED_INSTRUMENT = 'SET_SELECTED_INSTRUMENT';

//Linker
export const LINKER_REQUEST = 'LINKER_REQUEST';
export const SET_LINKER_REQUEST = 'SET_LINKER_REQUEST';
export const AUTO_START_LINKER = 'AUTO_START_LINKER';
export const REMOVE_STARTED_LINKER_AUTO = 'REMOVE_STARTED_LINKER_AUTO';
export const SET_EDIT_LINKER_PARAMETERS = 'SET_EDIT_LINKER_PARAMETERS';
///Order-Report
export const SET_ORDER_REPORT = 'SET_ORDER_REPORT';

//Resources
export const RESOURCE_REQUEST = 'RESOURCE_REQUEST';
export const SET_RESOURCE_REQUEST = 'SET_RESOURCE_REQUEST';

//Strategies
export const STRATEGIES_INFO = 'STRATEGIES_INFO';
export const SET_STRATEGIES_INFO = 'SET_STRATEGIES_INFO';

//Candle
export const CANDLE_REQUEST = 'CANDLE_REQUEST';
export const SET_CANDLE = 'SET_CANDLE';

//Setting
export const SETTING_REQUEST = 'SETTING_REQUEST';
export const SET_SETTING_REQUEST = 'SET_SETTING_REQUEST';

//SOCKET
export const SOCKET_INITIAL = 'SOCKET_INITIAL';
export const INCOMING_DATA = 'INCOMING_DATA';

//Notification Bar
export const SET_NOTIFICATION_BAR = 'SET_NOTIFICATION_BAR';
export const NOTIFICATION_BAR = 'NOTIFICATION_BAR';

//ORDER TRUE WAY
export const SET_ORDER_TRUE_WAY = 'SET_ORDER_TRUE_WAY';

//Loading App component
export const SET_APP_LOADING = 'SET_APP_LOADING';